name 'danieldreier-thin'
version '0.1.0'
source 'https://github.com/danieldreier/puppet-thin'
author 'Camptocamp DevOps Team / Daniel Dreier'
license 'GNU GPLv3'
summary 'Forked version of camptocamp Thin Module'
description 'Thin Module for Puppet'
project_page 'https://github.com/danieldreier/puppet-thin'
